// <auto-generated />
namespace WebApiLocadora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Create_DDL_Inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_DDL_Inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201911150300377_Create_DDL_Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
